nelmio_api_doc:
    documentation:
        servers:
            - url: https://localhost:8000/api
              description: API over HTTPS
        info:
            title: Sides Api App
            description: This is a test app!
            version: 0.1.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
