controllers:
    resource: ../src/Controller/
    type: attribute

register:
    path: /register
    controller: App\Controller\AuthController::register
    methods:
        - GET
        - POST

api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser
    methods:
        - POST

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

#test:
#    path: /api/test
#    controller: App\Controller\ApiController::test
